### ISSUE TITLE
Process new log entries only

### ISSUE THREAD

**Issue by gservat** [lukewaite/logstash-input-cloudwatch-logs#14]
Since I'm running logstash in a container, which could potentially die for reasons, it would be good if this plugin would allow you to process new logs only otherwise log messages will get sent to the "output" every time logstash is restarted.

I haven't looked at the code closely yet, but would this be a simple matter of setting `last_read` to `last_ingestion_time` for each stream when the app is first started? If `process_new_events_only` is true, that is.

**Comment by lukewaite** [comment]
@gservat I'm running logstash in a container as well, but mounting in a volume for the sincedb files, so that if logstash exits for any reason, it restarts from where it left off.

I'm not sure that I want to change the default behaviour, but I'd be open to a PR on the input to optionally begin from the current time.

**Comment by lukewaite** [comment]
Implemented in v1.0. The plugin now supports a `start_position` option.
https://github.com/lukewaite/logstash-input-cloudwatch-logs#parameters
