### ISSUE TITLE
Support `start_position` setting

### ISSUE THREAD

**Issue by lukewaite** [lukewaite/logstash-input-cloudwatch-logs#28]
When the plugin is starting, if a `log_group` is encountered that is not in the SinceDB, the `start_position` setting will allow the user to specify where to begin ingestion.

Available settings would be:
* `beginning` (default)
* `end`
* integer (seconds ago from now)

While running, if new log groups are encountered (because you've set `log_group_prefix` to `true`) this setting will be ignored, and all log entries in the group will be ingested as we are making the presumption that the stream will all be desired.

This is mimicking the behaviour of the `logstash-input-s3` plugin's `start_position`, while adding the ability to start at `now()-n minutes`.

Updated: Setback in seconds now, not minutes.

**Comment by lukewaite** [comment]
@chris-west-travelex I think this change would essentially do what your [PR](https://github.com/lukewaite/logstash-input-cloudwatch-logs/pull/25) from a few months back was adding in to your own fork.

Does this behaviour meet your need?

**Comment by chris-west-travelex** [comment]
@lukewaite yes, almost certainly -- thanks!

For a bit more context: we run logstash in a stateless docker container, which means that sincedb and similar mechanisms don't work very well, because each time the container restarts it loses its state. Instead we assume that we won't have a logstash outage of more than 60 mins and that the downstream systems can cope with duplicates. (ES certainly can, because it UPSERTS records).

I think the ideal for our particular (no doubt specific to Travelex) use-case would be to write the sincedb metadata to another AWS service for persistence. DynamoDB maybe? Even better, perhaps there could be a smart way of writing events back to CloudWatch Logs to track the plugin's progress. Regardless, having `start_position` is enough for us :)

**Comment by lukewaite** [comment]
@chris-west-travelex Sounds good, thanks! 

I won't make any promises on storing sincedb to another location at this point - it's something I've given thought to in the past, but I don't want to creep too much before releasing a stable v1.

**Comment by lukewaite** [comment]
@chris-west-travelex Implemented, and released under the `v1.0.0.rc1` release.

I've implemented on my own side, starting from an hour back, and it seems solid to me. Greatly simplifies deployment of my logstash container.
