### ISSUE TITLE
Error: can't convert nil into String

### ISSUE THREAD

**Issue by nvasion** [lukewaite/logstash-input-cloudwatch-logs#29]
I keep getting this error when I start up logstash.
 `Error: can't convert nil into String`

I am also trying to do Docker AWS Logger like #24. I have a single log group example below
`input {
  cloudwatch_logs {
    log_group => [ "myservice" ]
    region => "eu-west-1"
    access_key_id => ""
    secret_access_key => ""
  }
}`

The logs have a prefix like looks like this SERVICE/SERVICE/ID. Am I doing something wrong?

Thanks.

**Comment by lukewaite** [comment]
@nvasion Ah, I believe you're hitting this issue because the README has been updated for the next major release, but logstash won't install that unless you specifically request the pre-release.

In the [version you likely have installed](https://github.com/lukewaite/logstash-input-cloudwatch-logs/tree/v0.10.3) the `log_group` param must be a string.

If you want to update to the latest pre-release, that supports array syntax, you can run the plugin install for the pre-release version: `logstash-plugin install --version 1.0.0.rc1 logstash-input-cloudwatch_logs` I've been running in prod for a few days now without issue.

Also, since you mention prefix, it should be noted you want to set `log_group_prefix => true` if you're only specifying a prefix, in either version.

**Comment by nvasion** [comment]
@lukewaite thanks for the quick reply. I just removed the array and made it a string however I still get the error.

Full Error below:
`[2017-07-06T20:29:03,074][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::CloudWatch_Logs log_group=>"service", region=>"eu-west-1", access_key_id=>"", secret_access_key=>"", id=>"c7387adc48b1b242112c80441308addd721875a9-4", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_5518aea0-660f-4fc1-8229-f4871baba9f1", enable_metric=>true, charset=>"UTF-8">, interval=>60, log_group_prefix=>true>
  Error: can't convert nil into String`

I will upgrade myself to the rc see if maybe it will help. Thanks.

**Comment by nvasion** [comment]
Upgrading to the Release candidate fixed it. When will the full version be released?

**Comment by lukewaite** [comment]
@nvasion I'm really just trying to sit on it for a few more days to see if there are any issues I'm not hitting myself. 

If I don't get any negative feedback about it before the end of the weekend, I'll probably tag the stable release on Monday.

**Comment by lukewaite** [comment]
@nvasion Stable release of v1.0.0 has been tagged and published.
