### ISSUE TITLE
Duplicate logs in Elasticsearch?

### ISSUE THREAD

**Issue by brokenthumbs** [lukewaite/logstash-input-cloudwatch-logs#48]
My ELK cluster is currently distributed across multiple containers. I have multiple Logstash containers, to help deal with Filebeat inputs, along with Cloudwatch Log inputs. Would there be any problem if I was running the cloudwatch_logs input on multiple Logstash containers going to the same Elasticsearch cluster? 

I've noticed multiple entries in my Elasticsearch cluster with the same cloudwatch_logs event_id. Without defining a document_id, I've seen multiple Elasticsearch entries for the same Cloudwatch log, based on duplicate cloudwatch_logs event_id. 

For now, I've mitigated the duplication by using the cloudwatch_logs event_id as a document_id for Elasticsearch, which would prevent duplicate entries. Is this behavior intended, or is there some other way to prevent duplicate Cloudwatch logs from being entered into my Elasticsearch cluster?

Thanks!

**Comment by lukewaite** [comment]
The behaviour is unfortunately intended; I don't believe that there is a way for the plugin to specify the document id - the output to ES must do that.

Because state is stored on a single node, running multiple copies against the same input source will lead to this issue.

I don't think it's something we can solve for at the plugin level. I'm not super familiar with the new 'pipelines' feature sets of logstash, but perhaps in the future we will be able to assign a given input to only a single node.

If you do need to run across multiple nodes (due to throughput) and have to solve for this, you may be better off investigating alternative methods for ingesting CWL data. 

You should be able to set up a kinesis stream of CWL data, then use the logstash kinesis input to pull data. Kinesis would save state, and will probably work better for higher volume ingestion.

**Comment by brokenthumbs** [comment]
To update on this, I managed to add some filters to get the intended effect. Since I am not explicitly using the ES `document_id` for anything except for storing unique logs, this solution can effectively ignore the contents of `document_id`, as long as `document_id` is unique. 

Create a default `document_id` using the `uuid` filter. If the log is from `cloudwatch_logs`, override the `document_id` using `[cloudwatch_logs][event_id]`

Roughly as follows:
```
input {
  cloudwatch_logs {
    log_group => [ "/aws/lambda/", "/aws/rds/cluster/" ]
    log_group_prefix => true
  }
}

filter {

  uuid {
    target => "[@metadata][document_id]"
    overwrite => true
  }

  if [cloudwatch_logs] {
    mutate {
      replace => {
        "[@metadata][document_id]" => "%{[cloudwatch_logs][event_id]}"
      }
    }
  }

}

output {
  elasticsearch {
    action => "index"
    hosts => "__ELASTICSEARCH_URL__"
    password => "__ELASTICSEARCH_PASSWORD__"
    ssl => true
    ssl_certificate_verification => true
    user => "__ELASTICSEARCH_USERNAME__"
    document_id => "%{[@metadata][document_id]}"
  }
}
```
